export const ADMIN_USER_MEMORIES_REQUEST = 'ADMIN_USER_MEMORIES_REQUEST';
export const ADMIN_USER_MEMORIES_SUCCESS = 'ADMIN_USER_MEMORIES_SUCCESS';
export const ADMIN_USER_MEMORIES_FAILURE = 'ADMIN_USER_MEMORIES_FAILURE';
export const ADMIN_USER_MEMORIES_RESET = 'ADMIN_USER_MEMORIES_RESET';
