export const ADMIN_USER_MEMORIES_REQUEST = 'ADMIN_USER_MEMORIES_REQUEST';
export const ADMIN_USER_MEMORIES_SUCCESS = 'ADMIN_USER_MEMORIES_SUCCESS';
export const ADMIN_USER_MEMORIES_FAILURE = 'ADMIN_USER_MEMORIES_FAILURE';
export const ADMIN_USER_MEMORIES_RESET = 'ADMIN_USER_MEMORIES_RESET';

// Make or remove suspension
export const ADMIN_SUSPEND_USER_REQUEST = 'ADMIN_SUSPEND_USER_REQUEST';
export const ADMIN_SUSPEND_USER_SUCCESS = 'ADMIN_SUSPEND_USER_SUCCESS';
export const ADMIN_SUSPEND_USER_FAILURE = 'ADMIN_SUSPEND_USER_FAILURE';
