export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_MEMORIES_REQUEST = 'USER_MEMORIES_REQUEST';
export const USER_MEMORIES_SUCCESS = 'USER_MEMORIES_SUCCESS';
export const USER_MEMORIES_FAILURE = 'USER_MEMORIES_FAILURE';
export const USER_MEMORIES_RESET = 'USER_MEMORIES_RESET';

export const USER_CREATE_MEMORY_REQUEST = 'USER_CREATE_MEMORY_REQUEST';
export const USER_CREATE_MEMORY_SUCCESS = 'USER_CREATE_MEMORY_SUCCESS';
export const USER_CREATE_MEMORY_FAILURE = 'USER_CREATE_MEMORY_FAILURE';
