export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_MEMORIES_REQUEST = 'USER_MEMORIES_REQUEST';
export const USER_MEMORIES_SUCCESS = 'USER_MEMORIES_SUCCESS';
export const USER_MEMORIES_FAILURE = 'USER_MEMORIES_FAILURE';
export const USER_MEMORIES_RESET = 'USER_MEMORIES_RESET';

export const USER_CREATE_MEMORY_REQUEST = 'USER_CREATE_MEMORY_REQUEST';
export const USER_CREATE_MEMORY_SUCCESS = 'USER_CREATE_MEMORY_SUCCESS';
export const USER_CREATE_MEMORY_FAILURE = 'USER_CREATE_MEMORY_FAILURE';

export const USER_DELETE_MEMORY_REQUEST = 'USER_DELETE_MEMORY_REQUEST';
export const USER_DELETE_MEMORY_SUCCESS = 'USER_DELETE_MEMORY_SUCCESS';
export const USER_DELETE_MEMORY_FAILURE = 'USER_DELETE_MEMORY_FAILURE';

export const USER_DELETE_MEMORY_TAG_REQUEST = 'USER_DELETE_MEMORY_TAG_REQUEST';
export const USER_DELETE_MEMORY_TAG_SUCCESS = 'USER_DELETE_MEMORY_TAG_SUCCESS';
export const USER_DELETE_MEMORY_TAG_FAILURE = 'USER_DELETE_MEMORY_TAG_FAILURE';

export const USER_UPDATE_MEMORY_REQUEST = 'USER_UPDATE_MEMORY_REQUEST';
export const USER_UPDATE_MEMORY_SUCCESS = 'USER_UPDATE_MEMORY_SUCCESS';
export const USER_UPDATE_MEMORY_FAILURE = 'USER_UPDATE_MEMORY_FAILURE';

export const USER_UPDATE_MEMORY_SET_DUE_DATE_REQUEST =
  'USER_UPDATE_MEMORY_SET_DUE_DATE_REQUEST';
export const USER_UPDATE_MEMORY_SET_DUE_DATE_SUCCESS =
  'USER_UPDATE_MEMORY_SET_DUE_DATE_SUCCESS';
export const USER_UPDATE_MEMORY_SET_DUE_DATE_FAILURE =
  'USER_UPDATE_MEMORY_SET_DUE_DATE_FAILURE';

export const USER_UPDATE_MEMORY_IS_COMPLETE_REQUEST =
  'USER_UPDATE_MEMORY_IS_COMPLETE_REQUEST';
export const USER_UPDATE_MEMORY_IS_COMPLETE_SUCCESS =
  'USER_UPDATE_MEMORY_IS_COMPLETE_SUCCESS';
export const USER_UPDATE_MEMORY_IS_COMPLETE_FAILURE =
  'USER_UPDATE_MEMORY_IS_COMPLETE_FAILURE';

// UPDATE forgotten password
export const USER_UPDATE_FORGOT_PASSWORD_REQUEST =
  'USER_UPDATE_FORGOT_PASSWORD_REQUEST';
export const USER_UPDATE_FORGOT_PASSWORD_SUCCESS =
  'USER_UPDATE_FORGOT_PASSWORD_SUCCESS';
export const USER_UPDATE_FORGOT_PASSWORD_FAILURE =
  'USER_UPDATE_FORGOT_PASSWORD_FAILURE';

// Request new password if forgotten (SEND EMAIL)
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAILURE = 'USER_FORGOT_PASSWORD_FAILURE';

// UPDATE new password if forgotten
export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAILURE = 'USER_UPDATE_PASSWORD_FAILURE';
